server: 
    port: 8091
    servlet:
      context-path: /Exam
spring:
    datasource:
        username: root
        password: qwe123
        url: jdbc:mysql://localhost:3306/examination?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
        driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf: 
      cache: true        
    devtools: 
      restart: 
        enabled: true
        
mybatis:
    mapper-locations: classpath:mapper/*.xml
    config-locations: classpath:mybatis.xml
    type-aliases-package: com.oxy.model
    
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#  mapper-locations=classpath: mapper/*.xml 
