server: 
    port: 8088
    servlet:
      context-path: /Exam
spring:
    datasource:
        username: root
        password: qwe123
        url: jdbc:mysql://localhost:3306/examination?serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        
mybatis:
  configuration:
    mapper-locations: classpath*:mapper/*Mapper.xml
    config-locations: classpath:mybatis.xml

#  mapper-locations=classpath: mapper/*.xml 
